import { promises as fs } from "fs";
import path from "path";
import JSZip from "jszip";
import { assetsDir, loadProject } from "@/lib/projects/store";
import type { BusinessAsset, BusinessProject, SiteComposition } from "@/lib/types";

export async function exportSiteZip(businessId: string): Promise<Buffer | null> {
  const file = await loadProject(businessId);
  if (!file) return null;

  // Rewrite asset URLs to relative paths so the static bundle is self-contained.
  const localAssets: BusinessAsset[] = file.project.assets.map((a) => ({
    ...a,
    url: `./assets/${a.filename}`,
  }));

  const html = await renderHtml(file.project, file.composition, localAssets);

  const zip = new JSZip();
  zip.file("index.html", html);
  zip.file("README.txt", buildReadme(file.project));

  // Copy assets into zip.
  if (localAssets.length > 0) {
    const dir = assetsDir(businessId);
    for (const a of localAssets) {
      try {
        const buf = await fs.readFile(path.join(dir, a.filename));
        zip.file(`assets/${a.filename}`, buf);
      } catch {
        // skip missing
      }
    }
  }

  return zip.generateAsync({ type: "nodebuffer" });
}

async function renderHtml(
  project: BusinessProject,
  composition: SiteComposition,
  assets: BusinessAsset[]
): Promise<string> {
  // Dynamic imports keep these heavy server modules out of the App Router static graph.
  const [{ renderToStaticMarkup }, { default: RenderCompositionStatic }] = await Promise.all([
    import("react-dom/server"),
    import("@/components/render/RenderCompositionStatic"),
  ]);

  const body = renderToStaticMarkup(
    RenderCompositionStatic({ composition, assets })
  );

  const fontFamily = composition.theme.fontFamily;
  const usesPlayfair = fontFamily.includes("Playfair");

  const fontLink = usesPlayfair
    ? '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Playfair+Display:wght@500;600;700&display=swap" rel="stylesheet">'
    : '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">';

  const title = escapeHtml(project.input.businessName);
  const description = escapeHtml(
    project.input.differentiator ||
      `${project.input.businessName} — ${project.input.businessType} in ${project.input.location}.`
  );

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${title}</title>
<meta name="description" content="${description}" />
${fontLink}
<style>
  *, *::before, *::after { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; -webkit-font-smoothing: antialiased; }
  body { font-family: ${fontFamily}; }
  a { text-decoration: none; }
</style>
</head>
<body>
${body}
</body>
</html>`;
}

function buildReadme(project: BusinessProject): string {
  return `${project.input.businessName} — generated by Final Tool

How to deploy:
- Upload the contents of this folder to any static host (Netlify, Vercel, S3, GitHub Pages, etc.).
- index.html is the entry point. The /assets folder must be uploaded alongside it.

Generated: ${project.createdAt}
`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
